net3

diff --git a/0x08-networking_basics_2/2-change_your_home_IP b/0x08-networking_basics_2/2-change_your_home_IP
--- a/0x08-networking_basics_2/2-change_your_home_IP
+++ b/0x08-networking_basics_2/2-change_your_home_IP
@@ -1,7 +1,22 @@
 #!/usr/bin/env bash
-# this script will change your IP
-cp /etc/hosts ~/hosts.new
-sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
-echo "8.8.8.8 facebook.com" >> ~/hosts.new
-cp -f ~/hosts.new /etc/hosts
-rm ~/hosts.new
+#
+# Configure resolution of localhost to 127.0.0.2 and facebook.com to 8.8.8.8
+
+if (( ${UID:-$(id -u)} ))
+then
+  echo 'Must be run as root'
+  exit 1
+fi
+
+if ! tempfile="$(mktemp)"
+then
+  echo 'Unable to create temporary file'
+  exit 1
+fi
+
+{ printf '%s\t%s\n' 127.0.0.2 localhost
+  printf '%s\t%s\n' 8.8.8.8   facebook.com
+  cat /etc/hosts
+} > "${tempfile}"
+
+cat -- "${tempfile}" > /etc/hosts
